### ISSUE TITLE
Cutscenes not working with black/white screen

### ISSUE THREAD

**Issue by Erebus1245** [diegolix29/shadPS4#11]
Seems to be a recent issue i remember them working correctly before and they work fine in nightly builds so must be something specific in your builds, some screens from the Father Gascoigne Boss cutscene:

release-shadPS4-2024-12-26-9164b80:
![shadPS4 2024-12-26 11-48-50](https://github.com/user-attachments/assets/2e83ec5c-d02f-4fcf-a98c-cde43f7a60a4)

nightly 
shadps4-win64-qt-2024-12-25-5f9abd1

![shadps4 2024-12-26 11-50-35](https://github.com/user-attachments/assets/86bc18c5-2f31-482b-8b1f-fe2f30d7be8a)

Here is my save directly before the Boss if anyone wants to test it:

[CUSA03173.zip](https://github.com/user-attachments/files/18252217/CUSA03173.zip)

**Comment by diegolix29** [comment]
hi bro i just test it on my forks and it works nice 
![image](https://github.com/user-attachments/assets/1b49cf19-ca95-43b7-b810-58b3dd086ff5)
 no issues

**Comment by diegolix29** [comment]
do you have any mods? i also play with uncaped fps

**Comment by Erebus1245** [comment]
Just vertex explosion fix nothing else really and yes i play at 60 fps.

**Comment by diegolix29** [comment]
![image](https://github.com/user-attachments/assets/0b4592fb-19b2-41a0-bfc1-2825a85d6d14)
 just test it with ur save file too on partBB and is all ok

**Comment by Erebus1245** [comment]
Honestly dunno then i  will just stick to nightly for now no big deal.

**Comment by diegolix29** [comment]
Have u tried again today? Np bro its ok tho

**Comment by Erebus1245** [comment]
Tried it just now and it doesn't work, switched to nightly and it works fine.

**Comment by Erebus1245** [comment]
> Have u tried again today? Np bro its ok tho

Ok tried PartBB and it works fine just like nightly, only your main builds from here https://github.com/diegolix29/shadPS4/releases have the cutscenes not working for some reason.

**Comment by EmulaNoob** [comment]
If you having white/black flashings on screen but with the game UI working normal I was having it... only solved when I used DDU to clean my drivers and reinstalled my GPU latest drivers again...

**Comment by diegolix29** [comment]
Oh that makes sense as i do clean installation once every other day thanks for the comment

**Comment by Erebus1245** [comment]
> If you was having white/black flashings on screen but with the game UI working normal I was having it... only solved when I used DDU to clean my drivers and reinstalled my GPU latest drivers again...

No it's not the driver i just installed Hotfix Driver 566.45 for Indiana Jones yesterday and i always use DDU bevore a driver install.

Again only the fullBB branch has this issue for me in main, nightly and partBB the cutscenes work completely fine.

**Comment by Erebus1245** [comment]
Some screens so ppl don't think i'm talking nonsense or don't know what i'm doing:

fullbb cutscene not working:
![Screenshot 2024-12-27 133315](https://github.com/user-attachments/assets/9e80aad0-5803-4492-98f4-ef434f74a897)

mainbb cutscene working:
![Screenshot 2024-12-27 133021](https://github.com/user-attachments/assets/a23c38bd-e95e-4884-8555-151feb38b08e)

partbb cutscene also working:
![Screenshot 2024-12-27 133203](https://github.com/user-attachments/assets/7ff6a05b-3688-44b3-8576-daebc47e4ca1)

**Comment by diegolix29** [comment]
Thank you im gonna debug it today then thank you for the feedback 🙏

**Comment by diegolix29** [comment]
Fixed on the last commit of Full-BB

**Comment by diegolix29** [comment]
![image](https://github.com/user-attachments/assets/d90c8364-0914-4dab-99ec-9e9d56b5cd61)
