### ISSUE TITLE
Bloodborne freezes

### ISSUE THREAD

**Issue by VeryVeryCoolName** [diegolix29/shadPS4#12]
I'm only having this issue with the PartBB channel:

I constantly get random freezes when walking around the map that can take between 1 to 10 minutes to clear up. When the game unfreezes, random effects sometimes happen like enemies becoming invincible or getting teleported someplace else.

Posted two examples of these freezes [here](https://youtu.be/XkPmVxVgoWo) (earrape warning at 1:47) and [here](https://youtu.be/iJVxT2pMnds)

The only mod I'm using is vertex explosion fix. I tested these crashes with and without patches for the last 4 partbb versions. Playing the game at 30fps with the vblank divider set to 1 seems to make these freezes extremely rare, but they can still happen (only got 1 freeze when fighting Micolash, played for around 5 hours at 30fps).

These are the patches I usually play with:
![image](https://github.com/user-attachments/assets/2943e8b7-d6ac-4901-b4cc-99f346672172)

And this is the log for the second crash:
[shad_log.txt](https://github.com/user-attachments/files/18254986/shad_log.txt)

**Comment by diegolix29** [comment]
this is a known issue with the partbb thats why the particles aren on main,  i will be eventually worked on, i am trying small steps into it from time to time, but its that and some random glitched vertex explosions from particles the main reason those particles arent on main shad

**Comment by VeryVeryCoolName** [comment]
👍👍 I was confused since I didn't see anyone talk about it here and very few on discord

**Comment by dirtspike** [comment]
I had significant performance and stabilty problems with the partbb lately. The qt version from here work very well though!
