### ISSUE TITLE
Crash on receiving any trophy

### ISSUE THREAD

**Issue by mizarddo** [diegolix29/shadPS4#6]
A few seconds after receiving any trophy, the bloodborne crashes. Is there any fix? This issue is not present with original shadps4.

**Comment by mizarddo** [comment]
A few seconds after receiving any trophy, the bloodborne crashes. Is there any fix? This issue is not present with original shadps4.

**Comment by AndresMesem** [comment]
> A few seconds after receiving any trophy, the bloodborne crashes. Is there any fix? This issue is not present with original shadps4.

 I tried deleting any kind of file related to the trophies, but it just make the game looks awful, idk why

**Comment by diegolix29** [comment]
can u make sure you are on the last version? https://github.com/diegolix29/shadPS4/releases

**Comment by mizarddo** [comment]
Absolutely. I'm updating it several times a day to the latest pushed nightly.

**Comment by Missake212** [comment]
> Absolutely. I'm updating it several times a day to the latest pushed nightly.

Could you give more info on the crash? Like any mods installed? Any patches used? What OS?

**Comment by mizarddo** [comment]
Sure, I'm on windows 11, Ryzen 7600x, RTX 3070, I have two mods, an xbox button UI and Jump on L3, and I'm using these patches: Skip intro, disable chromatic aberration, disable http requests, 60 FPS, Force enable old hunters DLC, Disable Vsync.

**Comment by diegolix29** [comment]
can u send ur log here or on discord taggin missake or dmugetsu?

caus that issue was resolve so and i pretty much have the same stuff as main shad with only a couple of variations or hacks that doseent touch anything on that area

**Comment by walidsaeed** [comment]
Crashes when fighting any enemy

**Comment by AndresMesem** [comment]
i had the same issue, was the resolution.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Missake212** [comment]
> Crashes when fighting any enemy

What's your cpu and what resolution are you playing at ?

**Comment by vermilion00** [comment]
> Crashes when fighting any enemy

If you have an intel system and crash when getting hit, try installing the SFX Fix mod from nexusmods, that fixed it for me.
